### ISSUE TITLE
[AK Energy Stats] Discrepancies in monthly vs yearly EIA data

### ISSUE THREAD

**Issue by ianalexmac** [acep-uaf/ak-energy-statistics-2011_2021#29]
It seems as though there are discrepancies between aggregated monthly data and the annual reporting. The sum of monthly generation should equal the yearly generation, but it doesn't. 

Initially found by @sgcolt562 (in context of Matanuska Light & Power) and and @mckittre (Bradley Lake)

**Comment by eldobbins** [comment]
Think this got solved in AETR
